- name: Install Docker
  hosts: all
  roles:
    - geerlingguy.docker

# geerlingguy.docker does not add our user but creates docker group   
- name: Add user to docker group
  hosts: all
  tasks:
  - name: Add to group
    command: sudo usermod -aG docker osboxes
  
  - name: Restart service
    command: sudo systemctl restart docker
